const codeList = [
  "AF",
  "AL",
  "DZ",
  "AS",
  "AD",
  "AO",
  "AI",
  "AQ",
  "AG",
  "AR",
  "AM",
  "AW",
  "AU",
  "AT",
  "AZ",
  "BS",
  "BH",
  "BD",
  "BB",
  "BY",
  "BE",
  "BZ",
  "BJ",
  "BM",
  "BT",
  "BO",
  "BQ",
  "BA",
  "BW",
  "BV",
  "BR",
  "IO",
  "BN",
  "BG",
  "BF",
  "BI",
  "CV",
  "KH",
  "CM",
  "CA",
  "KY",
  "CF",
  "TD",
  "CL",
  "CN",
  "CX",
  "CC",
  "CO",
  "KM",
  "CD",
  "CG",
  "CK",
  "CR",
  "HR",
  "CU",
  "CW",
  "CY",
  "CZ",
  "CI",
  "DK",
  "DJ",
  "DM",
  "DO",
  "EC",
  "EG",
  "SV",
  "GQ",
  "ER",
  "EE",
  "SZ",
  "ET",
  "FK",
  "FO",
  "FJ",
  "FI",
  "FR",
  "GF",
  "PF",
  "TF",
  "GA",
  "GM",
  "GE",
  "DE",
  "GH",
  "GI",
  "GR",
  "GL",
  "GD",
  "GP",
  "GU",
  "GT",
  "GG",
  "GN",
  "GW",
  "GY",
  "HT",
  "HM",
  "VA",
  "HN",
  "HK",
  "HU",
  "IS",
  "IN",
  "ID",
  "IR",
  "IQ",
  "IE",
  "IM",
  "IL",
  "IT",
  "JM",
  "JP",
  "JE",
  "JO",
  "KZ",
  "KE",
  "KI",
  "KP",
  "KR",
  "KW",
  "KG",
  "LA",
  "LV",
  "LB",
  "LS",
  "LR",
  "LY",
  "LI",
  "LT",
  "LU",
  "MO",
  "MG",
  "MW",
  "MY",
  "MV",
  "ML",
  "MT",
  "MH",
  "MQ",
  "MR",
  "MU",
  "YT",
  "MX",
  "FM",
  "MD",
  "MC",
  "MN",
  "ME",
  "MS",
  "MA",
  "MZ",
  "MM",
  "NA",
  "NR",
  "NP",
  "NL",
  "NC",
  "NZ",
  "NI",
  "NE",
  "NG",
  "NU",
  "NF",
  "MP",
  "NO",
  "OM",
  "PK",
  "PW",
  "PS",
  "PA",
  "PG",
  "PY",
  "PE",
  "PH",
  "PN",
  "PL",
  "PT",
  "PR",
  "QA",
  "MK",
  "RO",
  "RU",
  "RW",
  "RE",
  "BL",
  "SH",
  "KN",
  "LC",
  "MF",
  "PM",
  "VC",
  "WS",
  "SM",
  "ST",
  "SA",
  "SN",
  "RS",
  "SC",
  "SL",
  "SG",
  "SX",
  "SK",
  "SI",
  "SB",
  "SO",
  "ZA",
  "GS",
  "SS",
  "ES",
  "LK",
  "SD",
  "SR",
  "SJ",
  "SE",
  "CH",
  "SY",
  "TW",
  "TJ",
  "TZ",
  "TH",
  "TL",
  "TG",
  "TK",
  "TO",
  "TT",
  "TN",
  "TR",
  "TM",
  "TC",
  "TV",
  "UG",
  "UA",
  "AE",
  "GB",
  "UM",
  "US",
  "UY",
  "UZ",
  "VU",
  "VE",
  "VN",
  "VG",
  "VI",
  "WF",
  "EH",
  "YE",
  "ZM",
  "ZW",
  "AX"
];

const countryList = [
  "Afeganistão",
  "Albânia",
  "Argélia",
  "Samoa Americana",
  "Andorra",
  "Angola",
  "Anguila",
  "Antártica",
  "Antígua e Barbuda",
  "Argentina",
  "Armênia",
  "Aruba",
  "Austrália",
  "Áustria",
  "Azerbaijão",
  "Bahamas ",
  "Bahrein",
  "Bangladesh",
  "Barbados",
  "Bielorrússia",
  "Bélgica",
  "Belize",
  "Benim",
  "Bermudas",
  "Butão",
  "Bolívia",
  "Bonaire",
  "Bósnia e Herzegovina",
  "Botsuana",
  "Ilha Bouvet",
  "Brasil",
  "Território Britânico do Oceano Índico ",
  "Brunei Darussalam",
  "Bulgária",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Camboja",
  "Camarões",
  "Canadá",
  "Ilhas Cayman ",
  "República Centro-Africana ",
  "Chade",
  "Chile",
  "China",
  "Ilha do Natal",
  "Ilhas Cocos",
  "Colômbia",
  "Comores ",
  "Congo",
  "Congo ",
  "Ilhas Cook ",
  "Costa Rica",
  "Croácia",
  "Cuba",
  "Curaçao",
  "Chipre",
  "República Tcheca",
  "Costa do Marfim",
  "Dinamarca",
  "Djibuti",
  "Dominica",
  "República Dominicana ",
  "Equador",
  "Egito",
  "El Salvador",
  "Guiné Equatorial",
  "Eritreia",
  "Estônia",
  "Eswatini",
  "Etiópia",
  "Ilhas Malvinas  [Malvinas]",
  "Ilhas Faroé ",
  "Fiji",
  "Finlândia",
  "França",
  "Guiana Francesa",
  "Polinésia Francesa",
  "Territórios do Sul da França ",
  "Gabão",
  "Gâmbia ",
  "Geórgia",
  "Alemanha",
  "Gana",
  "Gibraltar",
  "Grécia",
  "Groenlândia",
  "Granada",
  "Guadalupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guiné",
  "Guiné-Bissau",
  "Guiana",
  "Haiti",
  "Ilha Heard e Ilhas McDonald",
  "Santa Sé ",
  "Honduras",
  "Hong Kong",
  "Hungria",
  "Islândia",
  "Índia",
  "Indonésia",
  "Irã",
  "Iraque",
  "Irlanda",
  "Ilha de Man",
  "Israel",
  "Itália",
  "Jamaica",
  "Japão",
  "Jersey",
  "Jordânia",
  "Cazaquistão",
  "Quênia",
  "Kiribati",
  "Coreia do Norte",
  "Coreia do Sul",
  "Kuwait",
  "Quirguistão",
  "República Democrática Popular do Laos ",
  "Letônia",
  "Líbano",
  "Lesoto",
  "Libéria",
  "Líbia",
  "Listenstaine",
  "Lituânia",
  "Luxemburgo",
  "Macau",
  "Madagáscar",
  "Malawi",
  "Malásia",
  "Maldivas",
  "Mali",
  "Malta",
  "Ilhas Marshall ",
  "Martinica",
  "Mauritânia",
  "Maurício",
  "Maiote",
  "México",
  "Micronésia",
  "Moldávia",
  "Mônaco",
  "Mongólia",
  "Montenegro",
  "Montserrat",
  "Marrocos",
  "Moçambique",
  "Mianmar",
  "Namíbia",
  "Nauru",
  "Nepal",
  "Holanda ",
  "Nova Caledônia",
  "Nova Zelândia",
  "Nicarágua",
  "Níger ",
  "Nigéria",
  "Niue",
  "Ilha Norfolk",
  "Ilhas Marianas do Norte ",
  "Noruega",
  "Omã",
  "Paquistão",
  "Palau",
  "Palestina, Estado de",
  "Panamá",
  "Papua Nova Guiné",
  "Paraguai",
  "Peru",
  "Filipinas ",
  "Pitcairn",
  "Polônia",
  "Portugal",
  "Porto Rico",
  "Catar",
  "República da Macedônia do Norte",
  "Romênia",
  "Federação Russa ",
  "Ruanda",
  "Reunião",
  "São Bartolomeu",
  "Santa Helena, Ascensão e Tristão da Cunha",
  "São Cristóvão e Nevis",
  "Santa Lúcia",
  "São Martinho",
  "São Pedro e Miquelon",
  "São Vicente e Granadinas",
  "Samoa",
  "São Marinho",
  "São Tomé e Príncipe",
  "Arábia Saudita",
  "Senegal",
  "Sérvia",
  "Seicheles",
  "Serra Leoa",
  "Cingapura",
  "Sint Maarten",
  "Eslováquia",
  "Eslovênia",
  "Ilhas Salomão",
  "Somália",
  "África do Sul",
  "Ilhas Geórgia do Sul e Sandwich do Sul",
  "Sudão do Sul",
  "Espanha",
  "Sri Lanka",
  "Sudão ",
  "Suriname",
  "Svalbard e Jan Mayen",
  "Suécia",
  "Suíça",
  "República Árabe da Síria",
  "Taiwan, província da China)",
  "Tajiquistão",
  "Tanzânia, República Unida da",
  "Tailândia",
  "Timor-Leste",
  "Ir",
  "Toquelau",
  "Tonga",
  "Trindade e Tobago",
  "Tunísia",
  "Peru",
  "Turcomenistão",
  "Ilhas Turcas e Caicos ",
  "Tuvalu",
  "Uganda",
  "Ucrânia",
  "Emirados Árabes Unidos ",
  "Reino Unido da Grã-Bretanha e Irlanda do Norte ",
  "Ilhas Menores Distantes dos Estados Unidos ",
  "Estados Unidos da América ",
  "Uruguai",
  "Uzbequistão",
  "Vanuatu",
  "Venezuela",
  "Vietnã",
  "Ilhas Virgens",
  "Ilhas Virgens",
  "Wallis e Futuna",
  "Saara Ocidental",
  "Iémen",
  "Zâmbia",
  "Zimbábue",
  "Ilhas Aland"
];

var index;
var score = 0;
var lifes = 3;

function rnd() {
  return Math.floor(Math.random() * 249);
}

function options() {
  document.getElementById("option1").innerText = countryList[rnd()];
  document.getElementById("option2").innerText = countryList[rnd()];
  document.getElementById("option3").innerText = countryList[rnd()];
  document.getElementById("option4").innerText = countryList[rnd()];
}

function answer() {
  index = rnd();

  var num = Math.floor(Math.random() * 4) + 1;
  document.getElementById("option" + num).innerText = countryList[index];

  var flagAPI = "https://countryflagsapi.com/png/" + codeList[index];
  document.getElementById("flag").src = flagAPI;
}

function game() {
  if (lifes == 0) {
    alert("PERDEU!!");
  } else if (score == 5) {
    alert("GANHOU!!");
  } else {
    options();
    var index = answer();
  }
}

function btn1() {
  var option1 = document.getElementById("option1");
  if (option1.innerText == countryList[index]) {
    score++;
    alert("pontuação: " + score);
    game();
  } else {
    lifes--;
    alert("vidas restantes: " + lifes);
    game();
  }
}

function btn2() {
  var option2 = document.getElementById("option2");
  if (option2.innerText == countryList[index]) {
    score++;
    alert("pontuação: " + score);
    game();
  } else {
    lifes--;
    alert("vidas restantes: " + lifes);
    game();
  }
}

function btn3() {
  var option3 = document.getElementById("option3");
  if (option3.innerText == countryList[index]) {
    score++;
    alert("pontuação: " + score);
    game();
  } else {
    lifes--;
    alert("vidas restantes: " + lifes);
    game();
  }
}

function btn4() {
  var option4 = document.getElementById("option4");
  if (option4.innerText == countryList[index]) {
    score++;
    alert("pontuação: " + score);
    game();
  } else {
    lifes--;
    alert("vidas restantes: " + lifes);
    game();
  }
}